version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo Starting to build dbt artifact...
      - pip install --upgrade pip
      - pip install dbt-core==1.4.5
      - pip install dbt-redshift==1.4.0
      
  build:
    commands:
      - dbt deps
      - dbt compile --profiles-dir .
      - dbt build --profiles-dir .

  post_build:
    commands:
      - echo Build dbt artifact and models completed!